[2021-08-06 09:42:54,595] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 27884
[2021-08-06 09:42:56,007] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27884
[2021-08-06 09:43:01,381] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27884
[2021-08-06 09:43:12,787] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /dat_show/ HTTP/1.1" 200 27884
[2021-08-06 09:43:14,013] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27884
[2021-08-06 09:45:34,911] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /day_show/ HTTP/1.1" 200 27884
[2021-08-06 09:45:36,077] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27884
[2021-08-06 09:45:39,807] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /month_show/ HTTP/1.1" 200 27884
[2021-08-06 09:45:41,138] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27884
[2021-08-06 09:46:02,882] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /months_show/ HTTP/1.1" 200 26325
[2021-08-06 09:46:04,818] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27884
[2021-08-06 11:36:09,381] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 28277
[2021-08-06 11:36:11,108] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 28277
[2021-08-06 11:36:20,037] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /days_show/ HTTP/1.1" 200 28277
[2021-08-06 11:36:22,030] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 28277
[2021-08-06 11:37:08,345] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /days_show/ HTTP/1.1" 200 27968
[2021-08-06 11:37:09,821] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27968
[2021-08-06 12:07:05,291] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 27878
[2021-08-06 12:07:09,841] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 12:13:43,852] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 27878
[2021-08-06 12:13:45,632] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 12:14:01,950] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /months_show/
Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 259, in months_show
    monthsData = getMYData(data,datetype)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 155, in __init__
    ['aqi_index', 'aqi_rank', 'pm25', 'daytemp', 'nighttemp', 'daywind', 'nightwind']].astype(int)
  File "D:\Software\python\lib\site-packages\pandas\core\generic.py", line 5548, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\managers.py", line 604, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\managers.py", line 409, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\blocks.py", line 595, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "D:\Software\python\lib\site-packages\pandas\core\dtypes\cast.py", line 974, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas\_libs\lib.pyx", line 615, in pandas._libs.lib.astype_intsafe
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2021-08-06 12:14:02,283] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /months_show/ HTTP/1.1" 500 100526
[2021-08-06 12:14:04,919] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:15:06,774] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 27878
[2021-08-06 13:15:09,772] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:15:15,411] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /months_show/
Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 260, in months_show
    monthsData = getMYData(data,datetype)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 155, in __init__
    ['aqi_index', 'aqi_rank', 'pm25', 'daytemp', 'nighttemp', 'daywind', 'nightwind']].astype(int)
  File "D:\Software\python\lib\site-packages\pandas\core\generic.py", line 5548, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\managers.py", line 604, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\managers.py", line 409, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\blocks.py", line 595, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "D:\Software\python\lib\site-packages\pandas\core\dtypes\cast.py", line 974, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas\_libs\lib.pyx", line 615, in pandas._libs.lib.astype_intsafe
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2021-08-06 13:15:16,045] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /months_show/ HTTP/1.1" 500 100651
[2021-08-06 13:15:19,286] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:16:07,833] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /years_show/
Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 278, in years_show
    yearsData = getMYData(data,datetype)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 155, in __init__
    ['aqi_index', 'aqi_rank', 'pm25', 'daytemp', 'nighttemp', 'daywind', 'nightwind']].astype(int)
  File "D:\Software\python\lib\site-packages\pandas\core\generic.py", line 5548, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\managers.py", line 604, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\managers.py", line 409, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\Software\python\lib\site-packages\pandas\core\internals\blocks.py", line 595, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "D:\Software\python\lib\site-packages\pandas\core\dtypes\cast.py", line 974, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas\_libs\lib.pyx", line 615, in pandas._libs.lib.astype_intsafe
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[2021-08-06 13:16:08,149] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /years_show/ HTTP/1.1" 500 100474
[2021-08-06 13:16:10,090] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:35:07,646] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /months_show/ HTTP/1.1" 200 41052
[2021-08-06 13:35:09,493] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:36:04,537] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /years_show/ HTTP/1.1" 200 29089
[2021-08-06 13:36:06,203] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:37:26,321] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /months_show/ HTTP/1.1" 200 41052
[2021-08-06 13:37:28,637] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:39:35,820] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /months_show/ HTTP/1.1" 200 41040
[2021-08-06 13:39:37,621] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:39:46,288] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /days_show/ HTTP/1.1" 200 27878
[2021-08-06 13:40:20,704] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:40:20,719] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /days_show/ HTTP/1.1" 200 27878
[2021-08-06 13:40:22,910] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:41:55,153] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /months_show/ HTTP/1.1" 200 41040
[2021-08-06 13:41:58,019] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:44:02,084] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /years_show/ HTTP/1.1" 200 29089
[2021-08-06 13:44:10,449] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Software\python\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Personal\Project\weatherAnalysis\weatherCrawler\dashboard.py", line 242, in days_show
    data = DataFrame(data)
  File "D:\Software\python\lib\site-packages\pandas\core\frame.py", line 529, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
[2021-08-06 13:44:10,547] [basehttp.py:124] [basehttp:log_message] [ERROR]- "GET /favicon.ico HTTP/1.1" 500 73889
[2021-08-06 13:44:18,998] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /years_show/ HTTP/1.1" 200 29089
[2021-08-06 13:44:20,452] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
[2021-08-06 13:44:50,965] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /years_show/ HTTP/1.1" 200 29077
[2021-08-06 13:44:52,515] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /favicon.ico HTTP/1.1" 200 27878
